version: '3.8'

services:
    app:
        build:
            args:
                user: Lenon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - microservices

        # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - net

    db_app:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "appgestao"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_PASSWORD: "root"
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - net

networks:
    net:
        driver: bridge
