<template>
    <button
        class="
        inline-flex
        items-center
        px-4
        py-2
        bg-blue-800
        dark:bg-blue-700
        border
        border-transparent
        rounded-md
        font-semibold
        text-xs
        text-white
        dark:text-gray-200
        uppercase
        tracking-widest
        hover:bg-blue-700
        dark:hover:bg-blue-600
        focus:bg-blue-900
        dark:focus:bg-blue-800
        active:bg-blue-900
        dark:active:bg-blue-700
        focus:outline-none
        focus:ring-2
        focus:ring-indigo-500
        focus:ring-offset-2
        transition
        ease-in-out
        duration-150"
    >
        <slot />
    </button>
</template>
